import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Prefetched when the link is hovered or enters the viewport */}
         <nav className="flex gap-4 p-4 "> 
          <Link href="/">Home</Link>
          <Link href="/accordion">Accordion</Link>
          <Link href="/dropdown/">Dropdown</Link>
          <Link href="/text-input">Text Input</Link>
          <Link href="/radio">Radio</Link>
          {/* No prefetching */}
          <a href="/contact">Contact</a>
          </nav>
        {children}
        
        
        </body>
    </html>
  );
}
